services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./secrets:/run/secrets